vim.api.nvim_set_keymap("n", "<F4>", ":lua require'dap'.run_last()<CR>", {silent=true, noremap=true, desc="Re run the last debug adapter"})
vim.api.nvim_set_keymap("n", "<F5>", ":lua require'dap'.continue()<CR>", {silent=true, noremap=true, desc="Start debugger"})
vim.api.nvim_set_keymap("n", "<F11>", ":lua require'dap'.step_over()<CR>", {silent=true, noremap=true, desc="Step over"})
vim.api.nvim_set_keymap("n", "<F12>", ":lua require'dap'.step_into()<CR>", {silent=true, noremap=true, desc="Step into"})
vim.api.nvim_set_keymap("n", "<Home>",":lua require'dap'.step_out()<CR>", {silent=true, noremap=true, desc="Step out"})
vim.api.nvim_set_keymap("n", "<F6>", ":lua require'dap'.clear_breakpoints()<CR>", {silent=true, noremap=true, desc="Remove all breakpoints"})
vim.api.nvim_set_keymap("n", "<F7>", ":lua require'dap'.toggle_breakpoint()<CR>", {silent=true, noremap=true, desc="Toggle breakpoint"})
vim.api.nvim_set_keymap("n", "<F8>", ":lua require'dap'.set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>", {silent=true, noremap=true, desc="Set breakpoint with condition"})
vim.api.nvim_set_keymap("n", "<F9>", ":lua require'dap'.set_breakpoint(nil, nil, vim.fn.input('Log point message: '))<CR>", {silent=true, noremap=true, desc="Set breakpoint with log"})
vim.api.nvim_set_keymap("n", "<leader>dc", ":lua require'dap'.continue()<CR>", {silent=true, noremap=true, desc="Start debugger <F5>"})
vim.api.nvim_set_keymap("n", "<leader>dsr", ":lua require'dap'.step_over()<CR>", {silent=true, noremap=true, desc="Step over <F11>"})
vim.api.nvim_set_keymap("n", "<leader>dsi", ":lua require'dap'.step_into()<CR>", {silent=true, noremap=true, desc="Step into <F12>"})
vim.api.nvim_set_keymap("n", "<leader>dso", ":lua require'dap'.step_out()<CR>", {silent=true, noremap=true, desc="Step out <End>"})
vim.api.nvim_set_keymap("n", "<leader>dsb", ":lua require'dap'.step_back()<CR>", {silent=true, noremap=true, desc="Step back"})
vim.api.nvim_set_keymap("n", "<leader>dbc", ":lua require'dap'.clear_breakpoints()<CR>", {silent=true, noremap=true, desc="Remove all breakpoints <F6>"})
vim.api.nvim_set_keymap("n", "<leader>dB", ":lua require'dap'.toggle_breakpoint()<CR>", {silent=true, noremap=true, desc="Toggle breakpoint <F7>"})
vim.api.nvim_set_keymap("n", "<leader>dC", ":lua require'dap'.set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>", {silent=true, noremap=true, desc="Set breakpoint with condition <F8>"})
vim.api.nvim_set_keymap("n", "<leader>dL", ":lua require'dap'.set_breakpoint(nil, nil, vim.fn.input('Log point message: '))<CR>", {silent=true, noremap=true, desc="Set breakpoint with log <F9>"})
vim.api.nvim_set_keymap("n", "<leader>dr", ":lua require'dap'.repl.toggle()<CR>", {silent=true, noremap=true, desc="Toggle REPL"})
vim.api.nvim_set_keymap("n", "<leader>dl", ":lua require'dap'.run_last()<CR>", {silent=true, noremap=true, desc="Re run the last debug adapter <F4>"})
vim.api.nvim_set_keymap("n", "<leader>dt", ":lua require'dap'.terminate()<CR>", {silent=true, noremap=true, desc="Terminate the session"})
vim.api.nvim_set_keymap("n", "<leader>dh", ":lua require'dap'.run_to_cursor()<CR>", {silent=true, noremap=true, desc="Continue execution to the current cursor"})
